### ISSUE TITLE
Isi README mu

### ISSUE THREAD

**Issue by hadihammurabi** [hdinjos/Portoku#1]
Pengen tau isinya apa, tapi di README gak ngasih penjelasan secara umum.
Duh, bingung gan.

**Comment by hdinjos** [comment]
sorry gan, belum benerin readme, sementara masih seperti itu dulu, sebenarnya mau bikin aplikasi untuk membuat portofolio secara online, biasanya kan pakai office word atau semacamnya kan. dan juga belajar pakai sevelte biar update teknologi

**Comment by hadihammurabi** [comment]
Langsung bagusin gan, biar oke mata ini ngeliatnya

**Comment by hadihammurabi** [comment]
Karena diskusi gak berlanjut, saya izin tutup issue-nya ya, Mas @hdinjos
